services:
  - type: web
    name: kidzone-admin
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://kidzone-backend-s7to.onrender.com
